spring:
  config:
    import:
      - classpath:application.yaml
  data:
    mongodb:
      uri: ${MONGODB_URI}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

app:
  jwt:
    key: ${JWT_SECRET_KEY}
  oauth:
    callback:
      success: ${FRONTEND_HOSTNAME}/auth/oauth/callback/success
      failure: ${FRONTEND_HOSTNAME}/auth/oauth/callback/failure
  cloud:
    aws:
      region: ${AWS_REGION}
      s3:
        bucket: ${AWS_S3_BUCKET}
      credential:
        accessKey: ${AWS_ACCESS_KEY}
        secretKey: ${AWS_SECRET_KEY}
